# Generated by Django 5.0.1 on 2024-01-17 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_form_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['-is_checked', '-created']},
        ),
        migrations.AddField(
            model_name='form',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
    ]
